#spark.jars                         /opt/spark-jars/iceberg-spark-runtime-4.0_2.13-1.10.0.jar,/opt/spark-jars/sedona-spark-shaded-4.0_2.13-1.8.1.jar
#spark.sql.extensions               org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
#spark.sql.catalog.local            org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.local.type       hadoop
#spark.sql.catalog.local.warehouse  /opt/spark/warehouse
